# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-21 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.TextField()),
                ('response', models.TextField()),
                ('error', models.IntegerField(default=0, null=True)),
                ('error_stack', models.TextField()),
                ('created_date', models.DateTimeField(null=True)),
                ('modified_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
