# Generated by Django 3.0.4 on 2020-03-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_errorstack_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorstack',
            name='error_stack',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='errorstack',
            name='response',
            field=models.TextField(null=True),
        ),
    ]
