# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-22 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0003_auto_20200322_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorstack',
            name='error',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
